---
kind: pipeline
name: icekramel CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: archlinux:base-devel
    commands:
      - cd /drone/src
      - pacman -Sy bc curl cpio libyaml lib32-gcc-libs aarch64-linux-gnu-gcc arm-none-eabi-gcc --noconfirm
      - export KBUILD_BUILD_USER=misaka
      - export KBUILD_BUILD_HOST=tp-workstation
      - bash ./build.sh upload
